// Code generated by protoc-gen-go.
// source: bitchan.proto
// DO NOT EDIT!

/*
Package bitchan is a generated protocol buffer package.

It is generated from these files:
	bitchan.proto

It has these top-level messages:
	Block
	Transactions
	Transaction
	TransactionInput
	TransactionOutput
	Response
*/
package bitchan

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Block struct {
	PreviousBlockHash []byte  `protobuf:"bytes,1,opt,name=previous_block_hash,proto3" json:"previous_block_hash,omitempty"`
	TransactionsHash  []byte  `protobuf:"bytes,2,opt,name=transactions_hash,proto3" json:"transactions_hash,omitempty"`
	Timestamp         uint64  `protobuf:"varint,3,opt,name=timestamp" json:"timestamp,omitempty"`
	Nonce             uint64  `protobuf:"varint,4,opt,name=nonce" json:"nonce,omitempty"`
	Difficulty        float32 `protobuf:"fixed32,5,opt,name=difficulty" json:"difficulty,omitempty"`
}

func (m *Block) Reset()                    { *m = Block{} }
func (m *Block) String() string            { return proto.CompactTextString(m) }
func (*Block) ProtoMessage()               {}
func (*Block) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Block) GetPreviousBlockHash() []byte {
	if m != nil {
		return m.PreviousBlockHash
	}
	return nil
}

func (m *Block) GetTransactionsHash() []byte {
	if m != nil {
		return m.TransactionsHash
	}
	return nil
}

func (m *Block) GetTimestamp() uint64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *Block) GetNonce() uint64 {
	if m != nil {
		return m.Nonce
	}
	return 0
}

func (m *Block) GetDifficulty() float32 {
	if m != nil {
		return m.Difficulty
	}
	return 0
}

type Transactions struct {
	Transactions []*Transaction `protobuf:"bytes,1,rep,name=transactions" json:"transactions,omitempty"`
}

func (m *Transactions) Reset()                    { *m = Transactions{} }
func (m *Transactions) String() string            { return proto.CompactTextString(m) }
func (*Transactions) ProtoMessage()               {}
func (*Transactions) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Transactions) GetTransactions() []*Transaction {
	if m != nil {
		return m.Transactions
	}
	return nil
}

type Transaction struct {
	TransactionInputs  []*TransactionInput  `protobuf:"bytes,1,rep,name=transaction_inputs" json:"transaction_inputs,omitempty"`
	TransactionOutputs []*TransactionOutput `protobuf:"bytes,2,rep,name=transaction_outputs" json:"transaction_outputs,omitempty"`
	BoardIdentifier    string               `protobuf:"bytes,3,opt,name=board_identifier" json:"board_identifier,omitempty"`
	ResponseHash       []byte               `protobuf:"bytes,4,opt,name=response_hash,proto3" json:"response_hash,omitempty"`
}

func (m *Transaction) Reset()                    { *m = Transaction{} }
func (m *Transaction) String() string            { return proto.CompactTextString(m) }
func (*Transaction) ProtoMessage()               {}
func (*Transaction) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *Transaction) GetTransactionInputs() []*TransactionInput {
	if m != nil {
		return m.TransactionInputs
	}
	return nil
}

func (m *Transaction) GetTransactionOutputs() []*TransactionOutput {
	if m != nil {
		return m.TransactionOutputs
	}
	return nil
}

func (m *Transaction) GetBoardIdentifier() string {
	if m != nil {
		return m.BoardIdentifier
	}
	return ""
}

func (m *Transaction) GetResponseHash() []byte {
	if m != nil {
		return m.ResponseHash
	}
	return nil
}

type TransactionInput struct {
	PreviousTransactionHash  []byte `protobuf:"bytes,1,opt,name=previous_transaction_hash,proto3" json:"previous_transaction_hash,omitempty"`
	PreviousTransactionIndex int32  `protobuf:"varint,2,opt,name=previous_transaction_index" json:"previous_transaction_index,omitempty"`
	Signature                []byte `protobuf:"bytes,3,opt,name=signature,proto3" json:"signature,omitempty"`
	PubicKey                 []byte `protobuf:"bytes,4,opt,name=pubic_key,proto3" json:"pubic_key,omitempty"`
}

func (m *TransactionInput) Reset()                    { *m = TransactionInput{} }
func (m *TransactionInput) String() string            { return proto.CompactTextString(m) }
func (*TransactionInput) ProtoMessage()               {}
func (*TransactionInput) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *TransactionInput) GetPreviousTransactionHash() []byte {
	if m != nil {
		return m.PreviousTransactionHash
	}
	return nil
}

func (m *TransactionInput) GetPreviousTransactionIndex() int32 {
	if m != nil {
		return m.PreviousTransactionIndex
	}
	return 0
}

func (m *TransactionInput) GetSignature() []byte {
	if m != nil {
		return m.Signature
	}
	return nil
}

func (m *TransactionInput) GetPubicKey() []byte {
	if m != nil {
		return m.PubicKey
	}
	return nil
}

type TransactionOutput struct {
	Amount        int64  `protobuf:"varint,1,opt,name=amount" json:"amount,omitempty"`
	PublicKeyHash []byte `protobuf:"bytes,2,opt,name=public_key_hash,proto3" json:"public_key_hash,omitempty"`
}

func (m *TransactionOutput) Reset()                    { *m = TransactionOutput{} }
func (m *TransactionOutput) String() string            { return proto.CompactTextString(m) }
func (*TransactionOutput) ProtoMessage()               {}
func (*TransactionOutput) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *TransactionOutput) GetAmount() int64 {
	if m != nil {
		return m.Amount
	}
	return 0
}

func (m *TransactionOutput) GetPublicKeyHash() []byte {
	if m != nil {
		return m.PublicKeyHash
	}
	return nil
}

type Response struct {
	Name      string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Mail      string `protobuf:"bytes,2,opt,name=mail" json:"mail,omitempty"`
	Content   string `protobuf:"bytes,3,opt,name=content" json:"content,omitempty"`
	Timestamp uint64 `protobuf:"varint,4,opt,name=timestamp" json:"timestamp,omitempty"`
	// Set only when the response is successive message in the thread.
	PreviousResponseHash []byte `protobuf:"bytes,5,opt,name=previous_response_hash,proto3" json:"previous_response_hash,omitempty"`
	// Set only when the response is the first message in the thread.
	ThreadTitle string `protobuf:"bytes,6,opt,name=thread_title" json:"thread_title,omitempty"`
}

func (m *Response) Reset()                    { *m = Response{} }
func (m *Response) String() string            { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()               {}
func (*Response) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *Response) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Response) GetMail() string {
	if m != nil {
		return m.Mail
	}
	return ""
}

func (m *Response) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

func (m *Response) GetTimestamp() uint64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *Response) GetPreviousResponseHash() []byte {
	if m != nil {
		return m.PreviousResponseHash
	}
	return nil
}

func (m *Response) GetThreadTitle() string {
	if m != nil {
		return m.ThreadTitle
	}
	return ""
}

func init() {
	proto.RegisterType((*Block)(nil), "Block")
	proto.RegisterType((*Transactions)(nil), "Transactions")
	proto.RegisterType((*Transaction)(nil), "Transaction")
	proto.RegisterType((*TransactionInput)(nil), "TransactionInput")
	proto.RegisterType((*TransactionOutput)(nil), "TransactionOutput")
	proto.RegisterType((*Response)(nil), "Response")
}

func init() { proto.RegisterFile("bitchan.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 385 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x92, 0x3f, 0x6f, 0xdb, 0x30,
	0x10, 0xc5, 0x21, 0xdb, 0x72, 0xab, 0xb3, 0x5c, 0x5b, 0x74, 0xff, 0xc8, 0x2d, 0x50, 0xa8, 0x9a,
	0xb4, 0xd4, 0x05, 0xdc, 0x35, 0x53, 0xb6, 0x4c, 0x01, 0x82, 0xec, 0x02, 0x25, 0xd1, 0x11, 0x61,
	0x89, 0x14, 0xc8, 0x63, 0x10, 0x4f, 0xc9, 0x27, 0xc9, 0x67, 0x0d, 0x44, 0x39, 0x06, 0x0d, 0x67,
	0x3c, 0xde, 0x7b, 0xbc, 0x7b, 0x3f, 0x12, 0xe6, 0x05, 0xc7, 0xb2, 0xa6, 0x62, 0xd3, 0x29, 0x89,
	0x32, 0x35, 0xe0, 0x5f, 0x37, 0xb2, 0xdc, 0x93, 0x5f, 0xb0, 0xea, 0x14, 0x7b, 0xe4, 0xd2, 0xe8,
	0xbc, 0xe8, 0x4f, 0xf2, 0x9a, 0xea, 0x3a, 0xf6, 0x12, 0x2f, 0x0b, 0xc9, 0x1a, 0x22, 0x54, 0x54,
	0x68, 0x5a, 0x22, 0x97, 0x42, 0x0f, 0xad, 0x91, 0x6d, 0x45, 0x10, 0x20, 0x6f, 0x99, 0x46, 0xda,
	0x76, 0xf1, 0x38, 0xf1, 0xb2, 0x09, 0x99, 0x83, 0x2f, 0xa4, 0x28, 0x59, 0x3c, 0xb1, 0x25, 0x01,
	0xa8, 0xf8, 0x6e, 0xc7, 0x4b, 0xd3, 0xe0, 0x21, 0xf6, 0x13, 0x2f, 0x1b, 0xa5, 0x5b, 0x08, 0xef,
	0x9d, 0x0b, 0x49, 0x0a, 0xa1, 0x3b, 0x20, 0xf6, 0x92, 0x71, 0x36, 0xdb, 0x86, 0x1b, 0x47, 0x94,
	0xbe, 0x7a, 0x30, 0x73, 0x6a, 0xf2, 0x17, 0x88, 0xe3, 0xc9, 0xb9, 0xe8, 0x0c, 0xbe, 0x3b, 0x23,
	0xd7, 0x79, 0xd3, 0x77, 0xc8, 0x3f, 0x58, 0xb9, 0x72, 0x69, 0xd0, 0xea, 0x47, 0x56, 0x4f, 0x5c,
	0xfd, 0xad, 0x6d, 0x91, 0x18, 0x96, 0x85, 0xa4, 0xaa, 0xca, 0x79, 0xc5, 0x04, 0xf2, 0x1d, 0x67,
	0xca, 0x06, 0x0c, 0xc8, 0x37, 0x98, 0x2b, 0xa6, 0x3b, 0x29, 0x34, 0x1b, 0x50, 0xf4, 0x41, 0xc3,
	0xf4, 0x19, 0x96, 0x17, 0x53, 0xff, 0xc0, 0xfa, 0x84, 0xd5, 0x1d, 0xef, 0xc0, 0x4d, 0xe1, 0xe7,
	0x87, 0x12, 0x2e, 0x2a, 0xf6, 0x64, 0x29, 0xfb, 0x3d, 0x65, 0xcd, 0x1f, 0x04, 0x45, 0xa3, 0x98,
	0x5d, 0xc2, 0x82, 0xef, 0x4c, 0xc1, 0xcb, 0x7c, 0xcf, 0x0e, 0xc7, 0x05, 0xae, 0x20, 0xba, 0x8c,
	0xf1, 0x05, 0xa6, 0xb4, 0x95, 0x46, 0xa0, 0x1d, 0x37, 0x26, 0x3f, 0x60, 0xd1, 0x99, 0xa2, 0x19,
	0x8c, 0xce, 0x4b, 0xa6, 0x2f, 0x1e, 0x7c, 0xbe, 0x3b, 0xc6, 0x22, 0x21, 0x4c, 0x04, 0x6d, 0x99,
	0xf5, 0x04, 0x7d, 0xd5, 0x52, 0xde, 0x58, 0x61, 0x40, 0x16, 0xf0, 0xa9, 0x94, 0x02, 0x99, 0xc0,
	0x23, 0x8f, 0xb3, 0x3f, 0x30, 0x3c, 0xfa, 0x6f, 0xf8, 0x7e, 0x0a, 0x75, 0xce, 0xca, 0xb7, 0xdb,
	0x7f, 0x85, 0x10, 0x6b, 0xc5, 0x68, 0x95, 0x23, 0xc7, 0x86, 0xc5, 0xd3, 0xfe, 0xa2, 0x62, 0x6a,
	0x3f, 0xe5, 0xff, 0xb7, 0x00, 0x00, 0x00, 0xff, 0xff, 0xf3, 0x70, 0x01, 0xf0, 0xa5, 0x02, 0x00,
	0x00,
}
